all:
  ubuntu:
    webserver:
      hosts:
        node1:
        node2:
     
    dbserver:
      hosts:
        node3:
        DESKTOP-A6R0UFM:

    node1:
      ansible_hosts: 192.168.37.129

    node2:
      ansible_hosts: 192.168.37.130
      
   
    DESKTOP-A6R0UFM:
      ansible_hosts: 172.29.255.58
  
  
  
  
  
  # webserver:
  #   hosts:
  #     192.168.37.129
  #     192.168.37.130
  # dbserver:
  #   hosts:  
  #     172.29.255.58
      
